### PR TITLE
Do not copy downloaded dependencies to bundle dir

### PR DESCRIPTION
**Pull request by tkdchen**
Resolves: FACTORY-5982

Signed-off-by: Chenxiong Qi <cqi@redhat.com>

### CODE REVIEW

**Comment by mprahl** [comment]
@tkdchen on second thought, I think the directory structure for the Go cache of `deps/gomod/pkg/mod/cache/download` should still exist in the bundle so that applications that use Cachito can rely on the path existing.

**Comment by tkdchen** [comment]
@mprahl Could you please review #109 firstly? If that PR is accepted, it would be easy to fix this pr according to your comment. Thanks.

**Comment by lcarva** [comment]
> @tkdchen on second thought, I think the directory structure for the Go cache of `deps/gomod/pkg/mod/cache/download` should still exist in the bundle so that applications that use Cachito can rely on the path existing.

Alternatively, as long as we don't set the `environment_variables`, clients should not assume the `deps/gomod` directory exists.

**Comment by lcarva** [comment]
We should close this because of #111

**Pull request closed without merging**
