### PR TITLE
Add isort plugin for flake8 and fix import order for all Python files

### PR DESCRIPTION
**Pull request by serg-cymbaluk**
Signed-off-by: Serhii Tsymbaliuk <stsymbal@redhat.com>

### CODE REVIEW

**Review by tkdchen — APPROVED** [review]

**Comment by brunoapimentel** [comment]
LGTM :+1: 

I don't mind having this kind of check, and I think it could be helpful in stablishing a single, organized way of importing deps.

But I think some people had different opinions on the daily scrum, so maybe we could discuss it here?

@akhmanova, IIRC, you said something about this, right?

**Review by akhmanova — APPROVED** [review]
Thank you!

**Review by brunoapimentel — APPROVED** [review]

**Comment by brunoapimentel** [comment]
I guess we can rebase and merge this, wdyt?

**Comment by serg-cymbaluk** [comment]
@brunoapimentel 

> I guess we can rebase and merge this, wdyt?

Yes, lets merge.

**Pull request merged**
