### PR TITLE
Add Python 3.9 as supported in setup.py

### PR DESCRIPTION
**Pull request by elfosardo**
Also change python_requires=">=3.8" in setup.py and add Python 3 only mention.

### CODE REVIEW

**Comment by chmeliik** [comment]
Hi @elfosardo, good catch on this inconsistency. However, the problem is the opposite, we have failed to keep the `python_requires` value up to date - it should be `>=3.8` now.

May I ask what motivated this contribution? :-)

**Comment by elfosardo** [comment]
@chmeliik hi! I will change the PR to reflect that, to be honest I was a bit undecided also looking at the tox and github actions configs, where the tests are set for python 3.8 and 3.9 only

The reason of the contribution is that I started looking at the code because I'm very interested in the pip support, I saw the inconsistency, and I just thought to spend a couple of minutes to fix it :)

**Review by chmeliik — APPROVED** [review]
LGTM, thanks!

**Review by MartinBasti — APPROVED** [review]

**Comment by tkdchen** [comment]
:+1:

**Review by akhmanova — APPROVED** [review]
Thank you!

**Pull request merged**
