### PR TITLE
Set packages and dependencies counts for requests 

### PR DESCRIPTION
**Pull request by chmeliik**
CLOUDBLD-4727

All the required changes (and a bit of refactoring) for storing package and dependency counts in the database.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

### CODE REVIEW

**Comment by chmeliik** [comment]
Some things to note:
* The `/api/v1/requests` API endpoint still gets the package and deps counts by counting entries in the `request_package` and `request_dependency` tables rather than relying on the new attributes. That is expected, this will be changed later.
* I tested this with integration tests. The `*_count` values stored in the DB match what is being reported by `/api/v1/requests` in all cases except one - the test case for https://github.com/cachito-testing/cachito-pip-local-path.git. This test tests an expected failure. The api reports package and dep counts as 0, the value in the DB is `null`. IMO `null` is what we want.

**Comment by chmeliik** [comment]
@dcho5 feel free to take a look and give feedback if you have any :-)

**Review by tkdchen — APPROVED** [review]

**Comment by chmeliik** [comment]
Rebased on master. Also moved the `set_packages_and_deps_counts` call to `finalize_request()` and added a test for that

**Comment by chmeliik** [comment]
Added docstring to PackagesData init, not sure why flake8 didn't say anything before

**Review by tkdchen — APPROVED** [review]

**Pull request merged**
