### PR TITLE
Ensure go.sum update-to-date to include checksum of replaced dep's so…

### PR DESCRIPTION
**Pull request by tkdchen**
…urce

Signed-off-by: Chenxiong Qi <cqi@redhat.com>

### CODE REVIEW

**Comment by tkdchen** [comment]
Resolves CLOUDBLD-184

**Comment by tkdchen** [comment]
@athos-ribeiro `go.mod` is changed after `go mod edit -replace`. I'm a newbie of golang, I can't figure out what issue would happen if `go.mod` is changed. Could you please elaborate?

BTW, after `go mod edit -replace` and `go mod tidy`, both `go.mod` and `go.sum` are changed, I have no idea why don't need to save them and how the build could work as expected without saving those changes. Could you help to explain? Thanks.

**Comment by athos-ribeiro** [comment]
`go mod tidy` checks if the `go.mod` file information matches the module source code. It adds missing dependencies to the `go.mod` file and removes the unused ones (if any). Then it fixes go.sum to match the (possibly new) state of go.mod.

If anything is changed in `go.mod` at this point, it means that additional unnecessary dependencies were fetched or that cachito failed to provide required dependencies due to bogus information in the `go.mod` file provided by the upstream project.

Thus, it may make sense to always run `go mod tidy`. We could either use a reactive approach, where we run it after downloading the dependencies and we get the cachito request to fail due to bogus upstream `go.mod` file; or a proactive approach, where we run it before downloading the dependencies and if the `go.mod` file is changed, we just throw a warning to let the user know the upstream project file is incorrect. If we go for the latter approach, we would have to run `go mod tidy` twice to ensure the `go.sum` file is also correct.

WDYT?

Cc @mprahl @lcarva

**Comment by lcarva** [comment]
> `go mod tidy` checks if the `go.mod` file information matches the module source code. It adds missing dependencies to the `go.mod` file and removes the unused ones (if any). Then it fixes go.sum to match the (possibly new) state of go.mod.
> 
> If anything is changed in `go.mod` at this point, it means that additional unnecessary dependencies were fetched or that cachito failed to provide required dependencies due to bogus information in the `go.mod` file provided by the upstream project.

Good catch. If there are additional unnecessary  dependencies then there would be additional unexpected modifications in `go.mod`.  I don't think the second case is valid. If there are bogus references in `go.mod`, then `go mod download` should fail, no?

> 
> Thus, it may make sense to always run `go mod tidy`. We could either use a reactive approach, where we run it after downloading the dependencies and we get the cachito request to fail due to bogus upstream `go.mod` file; or a proactive approach, where we run it before downloading the dependencies and if the `go.mod` file is changed, we just throw a warning to let the user know the upstream project file is incorrect. If we go for the latter approach, we would have to run `go mod tidy` twice to ensure the `go.sum` file is also correct.

Having inaccurate information is a problem, so we should address this. Let's file a separate issue for always running `go mod tidy`. I'm not sure what's the best course of action to take if unnecessary dependencies are removed from `go.mod`. Failing the request seems straight forward. Otherwise, we'd also have to remove the unnecessary dependencies from the source bundle of the request. This shouldn't be part of this PR.

> 
> WDYT?

I think for this PR, we should simply run `go mod tidy` after replace.

1. Run `go mod edit -replace ...`
1. Run `go mod download`
1. (NEW) Run `go mod tidy`

Then in a follow up story, we can sort out what to do if there are unnecessary dependencies in `go.mod`. This may turn out to be extremely tricky in the case where there are unnecessary dependencies and `go mod edit -replace` was used.

> 
> Cc @mprahl @lcarva

**Comment by mprahl** [comment]
It looks like the tests passed in TravisCI but for some reason, TravisCI didn't mark the result on the PR.

**Comment by athos-ribeiro** [comment]
> Good catch. If there are additional unnecessary dependencies then there would be additional unexpected modifications in `go.mod`. I don't think the second case is valid. If there are bogus references in `go.mod`, then `go mod download` should fail, no?

Here I should have said that the file itself is bogus. I was thinking about the case where a dependency is missing in `go.mod` before running `go mod download`. The download command will succeed in this case. It seems that In both cases cachito will provide the sources. Either with extra dependencies (which will may never be noticed) or with missing dependencies (which should be noticed during build time).

> Having inaccurate information is a problem, so we should address this. Let's file a separate issue for always running `go mod tidy`. I'm not sure what's the best course of action to take if unnecessary dependencies are removed from `go.mod`. Failing the request seems straight forward. Otherwise, we'd also have to remove the unnecessary dependencies from the source bundle of the request. This shouldn't be part of this PR.

That's right. This PR does the job of fixing the `go.sum` in case of replacements.

**Comment by tkdchen** [comment]
@athos-ribeiro What is the difference between `unused ones` and `unnecessary dependencies` mentioned in your comment?

**Comment by athos-ribeiro** [comment]
I may have used them to refer to the same thing. An unused reference in `go.mod` would result in a an unnecessary dependency shipped in the final cachito bundle.

**Pull request merged**
