### PR TITLE
Add github action for combining dependabot PRs

### PR DESCRIPTION
**Pull request by chmeliik**
Courtesy of https://github.com/hrvey/combine-prs-workflow

This should let us combine successful dependabot PRs into one with the
click of a button.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

### CODE REVIEW

**Comment by chmeliik** [comment]
Let's merge this and test if it works, WDYT?

**Comment by nirzari** [comment]
+1 to merging and testing

**Review by ejegrova — APPROVED** [review]
LGTM :+1:

**Comment by lcarva** [comment]
LOL this is crazy! Did it work?

**Comment by chmeliik** [comment]
> LOL this is crazy! Did it work?

@lcarva It did! See for example #402

**Pull request merged**
