### PR TITLE
Update optionalDependencies in package.json

### PR DESCRIPTION
**Pull request by thrbkova**
* CLOUDBLD-3917

Signed-off-by: Tereza Hrbkova <thrbkova@redhat.com>

### CODE REVIEW

**Comment by brunoapimentel** [comment]
I was wondering if it might be a good idea to add a unit test to cover this new scenario (`optionalDependencies`). But then I saw that there is no test covering the `devDependencies` as well. :smile: 

If we do choose to add them, it does not seem to be a trivial task. So maybe we could do a pair programming session to help @thrbkova?

**Comment by nirzari** [comment]
> I was wondering if it might be a good idea to add a unit test to cover this new scenario (`optionalDependencies`). But then I saw that there is no test covering the `devDependencies` as well. 
> 
> If we do choose to add them, it does not seem to be a trivial task. So maybe we could do a pair programming session to help @thrbkova?

+1 for implementing unit test. Ideally even if the unit test doesn't exist for the code line we are changing, we expect a unit test to be added just because we are modifying that.

**Comment by tkdchen** [comment]
IIUC, `pkg_managers.yarn._replace_deps_in_package_json` should also be updated. The issue is expected the changes will work for both npm and yarn package managers.

**Comment by brunoapimentel** [comment]
Closing this PR since I'll be taking over this ticket.

**Pull request closed without merging**
