### PR TITLE
Add package_dir to missing setup.py warning message

### PR DESCRIPTION
**Pull request by elfosardo**
Also fix a little typo

### CODE REVIEW

**Comment by tkdchen** [comment]
Hi @elfosardo There is failure in CI.

**Comment by elfosardo** [comment]
@tkdchen yeah, forgot to commit the changes to the unit tests :facepalm:

**Comment by tkdchen** [comment]
@elfosardo Thanks :+1:

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

**Review by brunoapimentel — APPROVED** [review]

**Pull request merged**
