### PR TITLE
Migrate to Fedora 32

### PR DESCRIPTION
**Pull request by chmeliik**
Update base images, project metadata and CI jobs accordingly

### CODE REVIEW

**Comment by chmeliik** [comment]
Note that one integration test currently fails:
```
test_packages[gomod_packages-vendored_with_flag]
AssertionError: Found mismatches: ['modules.txt'] between /tmp/pytest-of-acmiel/pytest-6/test_packages_gomod_packages_v0/download_29/app/vendor /tmp/pytest-of-acmiel/pytest-6/test_packages_gomod_packages_v0/expected_data_app/cachito-testing-gomod-vendored-3604a4d/vendor.

diff /tmp/pytest-of-acmiel/pytest-6/test_packages_gomod_packages_v0/download_29/app/vendor/modules.txt /tmp/pytest-of-acmiel/pytest-6/test_packages_gomod_packages_v0/expected_data_app/cachito-testing-gomod-vendored-3604a4d/vendor/modules.txt 
5d4
< ## explicit
```

The solution proposed by @akhmanova is to remove the `## explicit` marker from the testing repo: https://github.com/cachito-testing/gomod-vendored/commit/3604a4d7990f5c9279f26dda783b7b9bce617ed4

Given that one of the reasons for upgrading is proper handling for these markers, should we keep it and fix the expected data instead? Or should that be a separate test?

**Review by akhmanova — COMMENTED** [review]
Thank you for changing the integration tests as well. Looks good to me :)  Let's wait for additional approval.

**Review by athos-ribeiro — COMMENTED** [review]
LGTM!

Unit tests fail with f33 setuptools version. Should be fixed upon a rebase (fix is in master and the PR seems to be slightly outdated).

**Review by athos-ribeiro — APPROVED** [review]
Integration tests are also OK when rebasing this on master!

**Review by nirzari — APPROVED** [review]

**Comment by chmeliik** [comment]
Rebased on master

**Pull request merged**
