### PR TITLE
Add checklist to pull requests

### PR DESCRIPTION
**Pull request by MartinBasti**
Maintaners should check checklist during reviews

Signed-off-by: Martin Basti <mbasti@redhat.com>

### CODE REVIEW

**Comment by brunoapimentel** [comment]
We also need to update the README in case any worker configuration is changed/added. 

https://github.com/release-engineering/cachito/blob/b713e76c2d4d6e1fde3db7e720766e59eeded499/README.md#L411

Do you think we should add a reminder to the checklist? Maybe just a general reminder to check if the README needs to be updated.

**Comment by serg-cymbaluk** [comment]
@MartinBasti 
One item, may be relevant here, is a DB schema review. We need to check if DB schema has been touched. If so, check the corresponding migration is provided.

**Review by akhmanova — APPROVED** [review]
LGTM!

**Review by serg-cymbaluk — APPROVED** [review]
LGTM

**Pull request merged**
