### PR TITLE
added tox to dev dependencies

### LINKED ISSUE #93: make: tox: No such file or directory
tox dependency is missing, so running `make test` as a first-time user I get an ugly failure with: 

```
make: tox: No such file or directory
```

### PR DESCRIPTION
**Pull request by gsaslis**
- Added missing tox dependency to dev env
- Makefile switched to tox version inside venv

Fixes #93

### CODE REVIEW

**Comment by gsaslis** [comment]
(sidenote: I'm a total beginner in the python world - please treat gently :D )

**Comment by mprahl** [comment]
@gsaslis thank you for the contribution but I will not accept this change. The main reason is that tox should be installed outside of the test environment via a system package or if one does not exist, then by using pip with the `--user` flag or in a separate virtualenv. By putting it in the `requirements-dev.txt` file, it insinuates that you must run `pip install -r requirements-dev.txt` before running the tests, which is not the case since tox handles virtualenv creation for the tests. `requirements-dev.txt` is more or less an implementation detail of the dependencies required by tox outside of the direct dependencies used by Cachito.

**Comment by gsaslis** [comment]
Thanks for taking the time to explain @mprahl !  This makes sense. 

I didn't have tox installed, so I was wondering. 

Does it perhaps make sense to have this added to the Makefile then (under `venv` target) ?

**Comment by mprahl** [comment]
@gsaslis yes, that is a good idea. Feel free to file a PR with that change.

**Pull request closed without merging**
