### PR TITLE
upgrade athens to v0.11.0

### PR DESCRIPTION
**Pull request by nirzari**
CLOUDBLD-3371

### CODE REVIEW

**Comment by nirzari** [comment]
Tested locally. docker-compose logs show the correct updated athens version

**Review by chmeliik — APPROVED** [review]
LGTM, just please make sure to pass the DCO check (Signed-off-by in commits)

**Review by akhmanova — APPROVED** [review]
Thank you, LGTM. I believe it can be merged as soon all cheks pass :)

**Comment by tkdchen** [comment]
:+1:

**Pull request merged**
